'use strict';
/* Mon SAEIV 1.0.28 — continuité de course lors d'une perte de réseau.
   Le GPS réel, les arrêts, les annonces et la progression restent locaux.
   Une copie compacte de la course active permet aussi une reprise après recharge de la PWA. */
(()=>{
  const COURSE_CACHE='mon-saeiv-active-course-v1';
  const PROGRESS_KEY='monSaeivActiveCourseProgressV128';
  const REQUEST_URL=()=>new URL('./__mon_saev_active_course_v128.json',document.baseURI).href;
  const q=id=>document.getElementById(id);
  let lastProgressWrite=0, courseSavePromise=null, recoveryOffered=false, restoring=false;
  const jsonClone=v=>v==null?v:JSON.parse(JSON.stringify(v));
  const isoDate=v=>{if(v==null)return null;if(v instanceof Date)return v.toISOString();if(typeof v==='string')return v;try{return new Date(v).toISOString()}catch{return null}};
  function compactCourse(){
    if(!state?.pattern||!state?.route)return null;
    const p=jsonClone(state.pattern), trip=state.run?.trip?jsonClone(state.run.trip):null;p.trips=trip?[trip]:[];const serviceId=trip?.service;
    return {schema:128,savedAt:new Date().toISOString(),dept:state.dept??null,networkType:state.networkType??null,route:jsonClone(state.route),pattern:p,services:serviceId&&state.services?.[serviceId]?{[serviceId]:jsonClone(state.services[serviceId])}:{},run:state.run?{trip,patternIndex:0,serviceDate:isoDate(state.run.serviceDate),originDeparture:isoDate(state.run.originDeparture)}:null,service:{mode:state.service?.mode||'regular',tadStops:[...(state.service?.tadStops||[])],requestedStops:[...(state.service?.requestedStops||[])],requestChimedStops:[...(state.service?.requestChimedStops||[])]}};
  }
  async function saveCourse(){const snap=compactCourse();if(!snap||!('caches'in window))return;if(courseSavePromise)return courseSavePromise;courseSavePromise=(async()=>{try{const c=await caches.open(COURSE_CACHE);await c.put(REQUEST_URL(),new Response(JSON.stringify(snap),{headers:{'Content-Type':'application/json','Cache-Control':'no-store'}}))}catch(e){console.warn('[Offline] sauvegarde course',e)}finally{courseSavePromise=null}})();return courseSavePromise}
  function posSnapshot(p){const c=p?.coords;if(!c)return null;return {timestamp:Number(p.timestamp||Date.now()),latitude:Number(c.latitude),longitude:Number(c.longitude),accuracy:Number(c.accuracy||0),altitude:Number.isFinite(c.altitude)?Number(c.altitude):null,altitudeAccuracy:Number.isFinite(c.altitudeAccuracy)?Number(c.altitudeAccuracy):null,heading:Number.isFinite(c.heading)?Number(c.heading):null,speed:Number.isFinite(c.speed)?Number(c.speed):null}}
  function saveProgress(force=false,p=state?.pos){if(!state?.running||state.mode!=='gps')return;const now=Date.now();if(!force&&now-lastProgressWrite<1800)return;lastProgressWrite=now;try{localStorage.setItem(PROGRESS_KEY,JSON.stringify({schema:128,savedAt:now,current:state.current,target:state.target,departed:!!state.departed,announced:!!state.announced,arrivalAnnounced:!!state.arrivalAnnounced,nextStopDueAt:Number.isFinite(state.nextStopDueAt)?Number(state.nextStopDueAt):null,firstLegDepartureSeen:!!state.firstLegDepartureSeen,midpointAnnounced:!!state.midpointAnnounced,reached:!!state.reached,minDist:Number.isFinite(state.minDist)?Number(state.minDist):null,lastAdvance:Number(state.lastAdvance||0),requestedStops:[...(state.service?.requestedStops||[])],tadStops:[...(state.service?.tadStops||[])],requestChimedStops:[...(state.service?.requestChimedStops||[])],position:posSnapshot(p)}))}catch(e){console.warn('[Offline] checkpoint progression',e)}}
  async function clearActiveCourse(){try{localStorage.removeItem(PROGRESS_KEY)}catch{}if('caches'in window)try{const c=await caches.open(COURSE_CACHE);await c.delete(REQUEST_URL())}catch{}}
  async function readSavedCourse(){let progress=null,course=null;try{progress=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'null')}catch{}if(!progress||progress.schema!==128||!('caches'in window))return null;try{const r=await (await caches.open(COURSE_CACHE)).match(REQUEST_URL());if(r)course=await r.json()}catch(e){console.warn('[Offline] lecture course',e)}return course?.schema===128?{course,progress}:null}
  function applyOfflinePill(){if(navigator.onLine||!state?.running||state.mode!=='gps')return;const pill=q('gpsPill');if(!pill)return;pill.className='pill on';pill.textContent='GPS actif · HORS LIGNE';pill.title='La course continue localement. Seuls les services Internet (radio, nouvelles cartes, recherches en ligne) sont indisponibles.'}
  function networkChanged(){if(!navigator.onLine){applyOfflinePill();try{status('Connexion Internet perdue : la course, le GPS, les arrêts et les annonces continuent localement. La radio et les nouvelles données en ligne peuvent être indisponibles.','busy')}catch{}saveCourse();saveProgress(true)}else if(state?.running){try{status('Connexion Internet rétablie. La course est restée active pendant la coupure.','ok')}catch{}}}
  addEventListener('offline',networkChanged,{passive:true});addEventListener('online',networkChanged,{passive:true});
  function buildRecoveryUi(saved){if(q('v128OfflineRecovery'))return;const c=saved.course,p=saved.progress,st=c.pattern?.stops?.[p.current],nx=c.pattern?.stops?.[p.target];document.body.insertAdjacentHTML('beforeend',`<div id="v128OfflineRecovery" class="v128-offline-recovery" role="dialog" aria-modal="true" aria-label="Reprendre la course"><section class="v128-offline-card"><div class="eyebrow">COURSE SAUVEGARDÉE</div><h2>Reprendre la course en cours ?</h2><p><strong>${esc(c.route?.short||'Ligne')}</strong> · ${esc(c.pattern?.headsign||c.pattern?.stops?.at(-1)?.name||'')}</p><p class="v128-offline-detail">Dernier arrêt : ${esc(st?.name||'—')}<br>Prochain arrêt : ${esc(nx?.name||'terminus')}<br>La reprise fonctionne même sans connexion Internet.</p><div class="v128-offline-actions"><button id="v128OfflineResume" class="primary" type="button">▶ Reprendre la course</button><button id="v128OfflineDiscard" type="button">Ignorer cette sauvegarde</button></div></section></div>`);if(!q('v128OfflineRecoveryStyle')){const s=document.createElement('style');s.id='v128OfflineRecoveryStyle';s.textContent=`.v128-offline-recovery{position:fixed;z-index:56000;inset:0;display:flex;align-items:center;justify-content:center;padding:16px;background:rgba(0,0,0,.82);backdrop-filter:blur(7px)}.v128-offline-card{width:min(560px,100%);padding:18px;border:1px solid #456477;border-radius:22px;background:linear-gradient(180deg,#102936,#081923);box-shadow:0 28px 80px rgba(0,0,0,.6)}.v128-offline-card h2{margin:4px 0 10px}.v128-offline-card p{margin:7px 0;color:#d4e1e7}.v128-offline-detail{padding:10px 11px;border:1px solid #365263;border-radius:12px;background:#071721;font-size:.78rem;line-height:1.5}.v128-offline-actions{display:grid;gap:8px;margin-top:13px}.v128-offline-actions button{min-height:50px}@media(max-width:600px){.v128-offline-recovery{align-items:flex-end;padding:0}.v128-offline-card{border-radius:22px 22px 0 0;padding-bottom:calc(18px + env(safe-area-inset-bottom))}}`;document.head.appendChild(s)}q('v128OfflineResume')?.addEventListener('click',()=>resumeSaved(saved).catch(e=>{console.error('[Offline] reprise',e);alert(`Reprise impossible : ${e?.message||e}`)}));q('v128OfflineDiscard')?.addEventListener('click',()=>{q('v128OfflineRecovery')?.remove();clearActiveCourse()})}
  async function resumeSaved(saved){if(restoring||state?.running)return;restoring=true;try{const c=saved.course,p=saved.progress;state.dept=c.dept;state.networkType=c.networkType??state.networkType;state.route=jsonClone(c.route);state.pattern=jsonClone(c.pattern);state.patterns=[state.pattern];state.services=jsonClone(c.services||{});state.run=c.run?{trip:jsonClone(c.run.trip),pattern:state.pattern,patternIndex:0,serviceDate:c.run.serviceDate?new Date(c.run.serviceDate):new Date(),originDeparture:c.run.originDeparture?new Date(c.run.originDeparture):null}:null;state.runOptions=state.run?[state.run]:[];state.service.mode=c.service?.mode||'regular';state.service.tadStops=new Set(c.service?.tadStops||p.tadStops||[]);state.service.requestedStops=new Set(c.service?.requestedStops||p.requestedStops||[]);state.service.requestChimedStops=new Set(c.service?.requestChimedStops||p.requestChimedStops||[]);state.service.requestAlertIndex=null;if(ui?.startStop){ui.startStop.innerHTML=(state.pattern.stops||[]).map((s,i)=>`<option value="${i}">${i+1}. ${esc(s.name)}</option>`).join('');ui.startStop.disabled=false;ui.startStop.value=String(Math.max(0,Number(p.current)||0))}prepareCourseGeometry();q('v128OfflineRecovery')?.remove();await startGps();state.current=Math.max(0,Number(p.current)||0);state.target=Number.isFinite(Number(p.target))?Number(p.target):nextOperationalStop(state.current);if(state.target===null)state.target=state.pattern.stops.length;state.departed=!!p.departed;state.announced=!!p.announced;state.arrivalAnnounced=!!p.arrivalAnnounced;state.nextStopDueAt=Number.isFinite(Number(p.nextStopDueAt))?Number(p.nextStopDueAt):null;state.firstLegDepartureSeen=!!p.firstLegDepartureSeen;state.midpointAnnounced=!!p.midpointAnnounced;state.reached=!!p.reached;state.minDist=Number.isFinite(Number(p.minDist))?Number(p.minDist):Infinity;state.lastAdvance=Number(p.lastAdvance||Date.now());state.service.requestedStops=new Set(p.requestedStops||[]);state.service.tadStops=new Set(p.tadStops||[]);state.service.requestChimedStops=new Set(p.requestChimedStops||[]);try{labels();renderRequestsButton();updateRequestAlert(false);drawRoute();updateDepartureDisplay();updateScheduleAdherence()}catch(e){console.warn('[Offline] rafraîchissement reprise',e)}saveCourse();saveProgress(true);applyOfflinePill();try{status(navigator.onLine?'Course restaurée. Le suivi GPS reprend.':'Course restaurée hors connexion. Le suivi GPS reprend sans Internet.','ok')}catch{}}finally{restoring=false}}
  async function maybeOfferRecovery(){if(recoveryOffered||state?.running)return;const auth=window.MonSAEIVAuthV13;if(auth&&auth.unlocked!==true)return;const saved=await readSavedCourse();if(!saved)return;if(Date.now()-Number(saved.progress.savedAt||0)>12*3600e3){clearActiveCourse();return}recoveryOffered=true;buildRecoveryUi(saved)}
  try{const baseEnter=enterDriver;enterDriver=function(mode){const r=baseEnter(mode);if(mode==='gps'){saveCourse();saveProgress(true)}return r};const baseProcess=processPos;processPos=function(p){const r=baseProcess(p);if(state?.mode==='gps'){saveProgress(false,p);applyOfflinePill()}return r};const baseAdvance=advance;advance=function(manual=false){const r=baseAdvance(manual);if(state?.mode==='gps')saveProgress(true);return r};const basePrevious=previous;previous=function(){const r=basePrevious();if(state?.mode==='gps')saveProgress(true);return r};const baseFinish=finish;finish=function(){clearActiveCourse();return baseFinish()}}catch(e){console.warn('[Offline] hooks de continuité',e)}
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&state?.running){saveCourse();saveProgress(true)}},{passive:true});addEventListener('pagehide',()=>{if(state?.running){saveCourse();saveProgress(true)}},{passive:true});const boot=()=>{setInterval(()=>maybeOfferRecovery().catch(()=>{}),900);setTimeout(()=>maybeOfferRecovery().catch(()=>{}),700)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
  window.MonSAEIVOfflineContinuity={save:()=>{saveCourse();saveProgress(true)},clear:clearActiveCourse,diagnostics:()=>({online:navigator.onLine,running:!!state?.running,mode:state?.mode||null,lastCheckpoint:lastProgressWrite})};
})();
