'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const read=f=>fs.readFileSync(f,'utf8');
const data=JSON.parse(read('data/antoni-company-lines-2026.json'));
const board=read('v165-exploitation-board.js'),view=read('v202-antoni-pilot.js');
for(const path of ['v165-exploitation-board.js','v202-antoni-pilot.js','v187-collaborative-planning.js'])
 new vm.Script(read(path),{filename:path});
assert.equal(data.organization_id,'533814ff-a356-4b65-ba94-c5ca36ce917a');
assert.equal(data.summary.total,199);
assert.equal(data.lines.length,199);
assert.equal(data.summary.byDept['57'],129);
assert.equal(data.summary.byDept['54'],70);
assert.equal(data.summary.byCategory.school,172);
assert.equal(data.summary.byCategory.regular,27);
assert.equal(data.summary.mapped,172);
assert.equal(data.summary.review.length,27);
assert.equal(new Set(data.lines.map(x=>x.department+'|'+x.line_code)).size,data.lines.length,'unique lines in enterprise');
assert(data.lines.filter(x=>x.department==='54'&&x.source_code.startsWith('E')).every(x=>x.category==='school'&&x.gtfs_route_id===null),'unmapped E lines must not be misclassified');
for(const code of ['54R460','54R461','54R465','54R466','54R468','54R469','54R471'])assert(data.lines.some(x=>x.line_code===code),'current 54 route '+code);
for(const code of ['57R026','57R027','57R084','57R166'])assert(data.lines.some(x=>x.line_code===code));
assert(board.includes("select('department,line_code,gtfs_route_id,start_date,end_date,active')"),'GTFS route associations in toolbox');
assert(board.includes('routeId(line.gtfs_route_id)===routeId(route?.id)'), 'accurate GTFS IDs for schools');
assert(board.includes('const draftSegments=allowed.filter(s=>assignmentFor(s)?.source'), 'draft selections can be deleted');
assert(board.includes('await planner.openDriverDraft(driverId,date)'), 'drafts must be locked');
assert(board.includes('await planner.saveDraft()'), 'persist edited drafts');
assert(board.includes('saveHidden(date,done)'), 'date-scoped pilot exclusion');
assert(board.includes('if(!antoniPilot())return'), 'isolate pilot state from global operator');
assert(view.includes("const isDispatcher=()=>"),'same operator UI for every company');
assert(view.includes('saeiv-shared-ops'),'consistent dispatch styling across organizations');
assert(view.includes("h.id='saeivWorkHeader'"),'shared dispatcher header');
assert(view.includes('saeivWorkToggle'),'same collapsible course toolbox for all');
console.log('ANTONI v1.0.114: 199 operator routes (172 GTFS, 27 pending), locked draft bulk removal and accessible company workspace validated');
