'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const read=x=>fs.readFileSync(x,'utf8');
const board=read('v165-exploitation-board.js');
const planning=read('v187-collaborative-planning.js');
for(const file of ['v165-exploitation-board.js','v187-collaborative-planning.js','v197-service-blocks.js'])new vm.Script(read(file),{filename:file});
assert(board.includes("for(const serviceMode of (antoniPilot()?['tad']:['regular']))"),'all trips loaded once in ANTONI pilot');
assert(board.includes('const reservation=Boolean(window.FluoDemandStopsV3124?.isFullReservationFor?.(route,pattern,run.trip))'),'only actual reserved GTFS trips become TAD');
assert(board.includes("serviceMode:antoniPilot()&&reservation?'tad':'regular'"),'regular trip remains regular');
assert(board.includes('type=routeFamily(route,dept)'),'school type remains school');
assert(board.includes("if(!run.trip?.service||!state?.services?.[run.trip.service])continue"),'missing GTFS calendars fail closed');
assert(board.includes("if(rd&&[rd.getFullYear()"),'each run constrained to requested service day');
assert(planning.includes('Tenancy changes data, not scoring rules'),'same economy engine for every company');
assert(planning.includes("const cost=x=>x.rank.incremental+x.rank.compactPenalty*.20+x.contractPenalty*.50"),'shared ranking balances HLP cost with compact day');
assert(planning.includes("const sameLine=(l,seg)=>"),'verified company route matching');
assert(planning.includes("economicRouting:true"),'pilot draft service blocks include economic options');
const ctx={window:{},console};vm.runInNewContext(read('v197-service-blocks.js'),ctx);
const make=(id,start,end,originCoords,destinationCoords)=>({id,date:'2026-10-19',type:'regular',line:'460',start,end,origin:'Départ',destination:'Arrivée',originCoords,destinationCoords,source:'auto_service'});
const park={lat:48.70,lon:6.20,name:'Stationnement'};
const farA={lat:48.705,lon:6.205},farB={lat:48.707,lon:6.207};
const service=[make('first','08:00','09:00',farA,farA),make('second','12:00','13:00',farB,farB)];
const normal=ctx.window.MonSAEIVServiceBlocksV197.compose(service,park,'2026-10-19');
const optimized=ctx.window.MonSAEIVServiceBlocksV197.compose(service,park,'2026-10-19',{economicRouting:true});
assert(normal.items.some(x=>x.type==='cut'),'legacy compose still has waiting/cut');
assert(optimized.items.some(x=>x.type==='cut'),'economic compose still has waiting/cut');
assert(optimized.items.some(x=>x.economicChoice==='depot'&&x.type==='cut'&&x.cut_percentage===0),'0-percent provisional depot cut');
assert(optimized.items.some(x=>x.economicChoice==='depot'&&x.type==='hlp')===false,'HLP keeps own source, no fictitious flag');
assert(optimized.items.filter(x=>x.type==='hlp').length>=3,'outbound and intermediate HLP around depot');
assert(!normal.items.some(x=>x.economicChoice),'non-pilot composer not changed');
console.log('ANTONI 1.0.115: real TAD vs regular GTFS days and opt-in economic HLP/cuts verified');
