'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const read=f=>fs.readFileSync(f,'utf8');
const line=read('v185-line-thermometer.js'),inbox=read('v188-driver-inbox.js'),audio=read('v131-speech.js');
for(const [name,s]of Object.entries({line,inbox,audio}))new vm.Script(s,{filename:name});
assert(line.includes("sideLine.textContent='🚏 Baromètre'"),'landscape barometer is explicitly labeled');
assert(line.includes('v185LandscapeSwitch'),'barometer switch exists in side cockpit');
assert(line.includes("sideMap.addEventListener('click',()=>setView('map'))"),'map returns on tap');
assert(line.includes("sideLine.addEventListener('click',()=>setView('line'))"),'barometer opens on tap');
assert(line.includes('#driver.v185-view-line .navmap-wrap{display:none!important}'),'map is hidden when barometer chosen');
assert(line.includes('#driver.v185-view-line #v185Line{display:block!important'),'barometer overrides V15 landscape hiding all other panels');
assert(line.includes("driver?.classList.toggle('v185-view-line',view==='line')"),'view class syncs with switch');
assert(line.includes("localStorage.setItem(KEY,view)"),'driver view is persistent');
assert(inbox.includes("const setup=q('setup');if(!setup)return"),'driver planning requires setup screen');
assert(inbox.includes("gpsPanel.insertAdjacentElement('afterend',open)"),'planning action belongs to setup, not navigation');
assert(!inbox.includes('document.body.appendChild(open)'), 'planning shortcut cannot float globally');
assert(!inbox.includes('#v188Open{position:fixed'),'no global fixed planning shortcut');
assert(audio.includes("indicator.hidden=!driving||!target"),'audio action visible only in driving controls');
assert(audio.includes("const target=isLandscape?side:portrait"),'audio action is part of responsive cockpit');
assert(audio.includes("prepareAudioFromGesture();btn.dataset.busy='1'"),'a real gesture must attempt iOS WebAudio unlock');
assert(audio.includes("say('Annonces vocales actives.'"),'audio restore includes audible confirmation');
assert(audio.includes("localStorage.setItem('fluoPassengerAnnouncementsEnabled','on')"),'restore explicitly enables passenger announcements');
assert(!audio.includes("toggle.click();"),'audio retry must never accidentally switch announcements back off');
assert(!audio.includes("position:fixed;bottom:max(12px"),'audio button cannot overlay map/cockpit');
console.log('SAEIV 1.0.102: navigation cockpit planning relocated; landscape Carte/Baromètre switch accessible; audio action has iOS gesture and voice feedback.');
