'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const voice=fs.readFileSync('v131-speech.js','utf8');
const responsive=fs.readFileSync('v199-cockpit-responsive.js','utf8');
for(const [file,src] of [['v131-speech.js',voice],['v199-cockpit-responsive.js',responsive]])new vm.Script(src,{filename:file});
assert(voice.includes("const control=event.target?.closest?.('#voiceTest')"),'homepage voice test must be intercepted');
assert(voice.includes("event.preventDefault();event.stopImmediatePropagation()"),'obsolete V12 speech test should not run twice');
assert(voice.includes('const probe=probeIOSMediaFromGesture()'),'native iOS audio must be primed synchronously from test tap');
assert(voice.includes('prepareAudioFromGesture();'),'same unlock as navigation announcements');
assert(voice.includes("try{say(text,{priority:150,kind:'system',ephemeral:false})}"),'home uses same priority audio queue and cloud voice as navigation');
assert(voice.includes("control.textContent='🔊 Écouter la voix'"),'test UI must reset');
assert(voice.includes("&&!(await unlockAnnouncementAudio())&&!announcementOutput.mediaUnlocked"),'native HTMLMedia unlock must allow cloud on iPhone if WebAudio is unavailable');
assert(responsive.includes('max-width:1000px'),'Android landscape footer wraps before buttons become unreadable');
assert(responsive.includes('repeat(4,minmax(0,1fr))'),'landscape narrow action buttons use two rows');
assert(responsive.includes('(orientation:portrait) and (max-width:800px)'),'Android portrait layout exists');
assert(responsive.includes('#driver .controls,#driver .sim-controls'),'Android portrait controls are real grid');
assert(responsive.includes('min-height:43px'),'Android portrait touch targets are usable');
assert(responsive.includes('env(safe-area-inset-left)'),'handle safe area');
console.log('SAEIV 1.0.104: audio homepage shares cockpit engine; iOS media unlock not blocked; Android portrait/landscape responsive contracts passed.');
