'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm');
const load=p=>fs.readFileSync(p,'utf8');
const sql=load('supabase/migrations/20261008210000_intuitive_segment_change_v196.sql');
const script=load('v195-intuitive-segment-change.js'),legacy=load('v174-grid-editor.js'),driver=load('v193-published-driver-edits.js');
for(const [path,s] of [['UI',script],['legacy',legacy],['driver',driver]])new vm.Script(s,{filename:path});
for(const key of ['saeiv_propose_segment_change','saeiv_propose_change(','saeiv_published_days','plan_items','private.current_org_id()','private.is_exploitation_for(o)','saeiv_planning_locks','legacy_published_baseline_imported','saeiv_change_requests','revoke all','grant execute'])assert(sql.includes(key),key);
assert(!sql.includes('update public.plan_items'), 'live legacy plan must not change');
assert(!sql.includes('delete from public.plan_items'), 'cannot silently remove existing trips');
assert(!sql.includes('update public.saeiv_published_days'),'existing official plan must be immutable before consent');
for(const key of ['Modifier un service','Ligne / segment supprimé','Ligne / segment de remplacement','Supprimer cette course sans remplacement','Enregistrer, recalculer et envoyer au conducteur','saeiv_propose_segment_change','saeiv_acquire_lock','saeiv_release_lock','estimate(old,replacement)','scoreCandidate'])assert(script.includes(key),key);
assert(legacy.includes('window.MonSAEIVSegmentChangeV195')&&legacy.includes('Des courses appartiennent à un planning officiellement publié'),'old editor must redirect and block destructive shortcuts');
assert(driver.includes('window.MonSAEIVSegmentChangeV195.open'),'per-driver edit shortcut must use one shared UI');
const context={window:{},document:{},console:{log(){}},crypto:{randomUUID:()=> '0000'},setTimeout(){}};
vm.runInNewContext(script,context);
const api=context.window.MonSAEIVSegmentChangeV195;
assert(api.tokensMatch('57 sarrebourg',{line:'57',start:'06:37',end:'07:20',origin:'Sarrebourg',destination:'Nancy'}));
assert(api.tokensMatch('nancy 06:37',{line:'57',start:'06:37',end:'07:20',origin:'Sarrebourg',destination:'Nancy'}));
assert(!api.tokensMatch('54',{line:'57',start:'06:37',end:'07:20',origin:'Sarrebourg',destination:'Nancy'}));
console.log('SAEIV 1.0.96: searchable lines, legacy migration, RPC consent and no-direct-mutation guards verified');
