'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const read=x=>fs.readFileSync(x,'utf8');
const audio=read('v131-speech.js'),responsive=read('v199-cockpit-responsive.js');
for(const [name,src]of Object.entries({audio,responsive}))new vm.Script(src,{filename:name});
assert(responsive.includes('overflow-y:auto!important'),'right-hand panel must be vertically scrollable on iPhone');
assert(responsive.includes('grid-template-columns:repeat(8,minmax(0,1fr))'),'eight landscape actions must fit');
assert(responsive.includes('grid-template-columns:repeat(4,minmax(0,1fr))'),'narrow landscape screen must wrap buttons into two rows');
assert(responsive.includes('overflow-x:hidden!important'),'no offscreen horizontal toolbar items');
assert(responsive.includes('#v131AudioActivate'),'audio test button visible within scrollable right cockpit');
assert(audio.includes("media.id='v131AnnouncementMedia'"),'use persistent iOS HTMLAudioElement');
assert(audio.includes('const started=media.play()'),'audio probe must call play() in trusted gesture without awaiting');
assert(audio.includes('const probe=probeIOSMediaFromGesture();'),'audio activation must launch offline beep');
assert(audio.includes('const ready=prepareAudioFromGesture();'),'retain Web Audio unlock');
assert(audio.indexOf('const probe=probeIOSMediaFromGesture();')<audio.indexOf('const [webReady,probeResult]=await Promise.all([ready,probe])'),'probe playback before any await');
assert(audio.includes('const wave=beepWav()'),'audio probe waveform generated locally without network');
assert(audio.includes('if(media&&announcementOutput.mediaUnlocked)'),'prefer unlocked HTMLMedia for actual iOS cloud MP3');
assert(audio.includes('playIOSCloudBlob(blob,cur,started,done,fallbackCloud)'),'fallback when native media reports async error');
assert(audio.includes("media.onerror=()=>onError?.('Lecture HTML Audio iPhone interrompue')"),'media error should not be confused with successful end');
assert(audio.includes("a.passengerEnabled=true")&&audio.includes("fluoPassengerAnnouncementsEnabled','on'"),'audio retry actually enables announcements');
assert(audio.includes("say('Annonces vocales actives.'"),'audible voice phrase follows probe');
assert(audio.includes("side.insertBefore(indicator,marker)"),'voice test control is placed above next stop/low panel items');
assert(!audio.includes("position:fixed;bottom:max(12px"),'no floating audio button covering map');
console.log('SAEIV 1.0.103: right-panel scroll, full-width responsive footer, iOS gesture probe and TTS HTMLMedia fallback checks OK.');
