'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const read=x=>fs.readFileSync(x,'utf8');
const p='supabase/migrations/';
const schema=read(p+'20261008200000_change_batches_v195.sql');
const propose=read(p+'20261008200100_batch_propose_v195.sql');
const finalize=read(p+'20261008200200_batch_finalize_v195.sql');
const guards=read(p+'20261008200300_batch_guards_v195.sql');
for(const s of ['saeiv_change_batches','batch_id uuid','response_exempt boolean','enable row level security','private.is_exploitation_for(organization_id)'])assert(schema.includes(s),s);
for(const s of ['private.current_org_id()','private.is_exploitation_for(o)','saeiv_planning_locks','for update','saeiv_published_days','saeiv_change_requests','saeiv_notifications','driver_unavailability','p_sick_driver','p_changes','exempt'])assert(propose.includes(s),s);
for(const s of ["status<>'accepted'","status<>'pending'","revision<>r.base_revision","saeiv_published_days","saeiv_change_batches","saeiv_batch_refusal_guard",'saeiv_change_requests'])assert(finalize.includes(s),s);
assert(guards.includes('x.batch_id is not null'),'single finalize and cancel cannot bypass batch');
assert(guards.match(/x.batch_id is not null/g).length===2);
const paths=['v165-exploitation-board.js','v187-collaborative-planning.js','v188-driver-inbox.js','v178-sick-reassignment.js','v193-published-driver-edits.js','v194-sick-approval-batches.js'];
for(const name of paths)new vm.Script(read(name),{filename:name});
const board=read(paths[0]),ui=read(paths[1]),inbox=read(paths[2]),sick=read(paths[3]),edit=read(paths[4]),automation=read(paths[5]);
assert(board.includes('data-v195-edit'));
assert(edit.includes('saeiv_propose_change')&&edit.includes('data-remove')&&edit.includes('saeiv_acquire_lock'));
assert(ui.includes('saeiv_finalize_change_batch')&&ui.includes('saeiv_cancel_change_batch')&&ui.includes('response_exempt'));
assert(ui.includes('!x.batch_id'),'no direct member finalize');
assert(inbox.includes('saeiv_respond_change')&&inbox.includes("p_response:response"));
assert(sick.includes('MonSAEIVSickApprovalV194.propose')||sick.includes('approval.propose(from,to,driver,reason)'));
assert(automation.includes('saeiv_propose_change_batch')&&automation.includes('saeiv_published_days')&&automation.includes('scoreCandidate'));
assert(!automation.includes("from('saeiv_published_days').update"),'cannot silently mutate official plans');
console.log('SAEIV 1.0.95: individual consent + batch all-accepted atomic publication contracts OK');
