'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const read=path=>fs.readFileSync(path,'utf8');
const ui=read('v202-antoni-pilot.js');
const board=read('v165-exploitation-board.js');
const weekly=read('v190-weekly-planning.js');
for(const file of ['v202-antoni-pilot.js','v165-exploitation-board.js','v190-weekly-planning.js']){
  new vm.Script(read(file),{filename:file});
}
assert(ui.includes("const permitted=()=>['dispatcher','admin']"),'one dispatcher UI for all company organizations');
assert(ui.includes('#v157Dispatch{background:#f3f5f7!important'),'recolor the entire old fixed dark shell, not just interior');
assert(ui.includes('#v157Dispatch .v157-top'),'style company header with same palette');
assert(ui.includes('#v165Board .v165-work'),'keep one readable, existing board');
assert(ui.includes('makeHeader(root);makeDates(root);makeZoom(root);'),'mount all actual controls');
assert(ui.includes("const start=q('v165Date'),end=q('v190End')"),'use existing date inputs and existing listeners');
assert(ui.includes("q('saeivStart').append(l1);q('saeivEnd').append(l2);"),'move the original date labels, not clones');
assert(ui.includes("openCalendar(id,b)"),'dedicated accessible calendar buttons');
assert(ui.includes("root.setAttribute('aria-modal','true')"),'calendar overlay accessible');
assert(ui.includes("calMonth.setMonth"),'calendar can change months');
assert(ui.includes("b.dataset.date"),'calendar day buttons truly select a day');
assert(ui.includes("el.dispatchEvent(new Event('change',{bubbles:true}))"),'date selection triggers original workflow');
assert(ui.includes("if(el===start&&end?.value&&end.value<value)"),'valid date interval start');
assert(ui.includes("if(el===end&&start?.value&&start.value>value)"),'valid date interval end');
assert(ui.includes("board().setDate(add(board().date||start.value,step))"),'day arrows change actual current board day');
assert(ui.includes("document.addEventListener('saeiv-board-updated',dateLabel)"),'visible date stays synchronized');
assert(!ui.includes('showPicker?.()'),'no duplicate native picker click reentrancy');
assert(ui.includes("body.saeiv-shared-ops.saeiv-hide-toolbox"),'responsive course panel toggle');
assert(ui.includes('--sa-track'),'grid zoom can be adjusted');
assert(weekly.includes("if(q('v165Date'))q('v165Date').value=from()"),'selected GTFS day never overwrites the input date interval');
assert(weekly.includes("get rangeStart(){return from()}"),'period start is explicitly accessible');
assert(weekly.includes("if(!S.busy)S.rangeStart=date.value"),'date input changes period start for every company');
assert(board.includes("await window.MonSAEIVOperationsBoardV165.setDate(date)"),'native date changes call board date setter');
assert(board.includes("multiSelected.clear();B.segments=[];"),'day changes discard stale segments');
const doc={readyState:'loading',addEventListener(){}},win={};
vm.runInNewContext(ui,{window:win,document:doc,Intl,Date,console},{timeout:1000});
assert.equal(win.MonSAEIVAntoniPilotV202.version,'1.0.117');
assert.equal(typeof win.MonSAEIVAntoniPilotV202.sync,'function');
console.log('v1.0.117: shared exploitation shell, functional calendar controls and date-range/day separation validated.');
