const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
const read=f=>fs.readFileSync(f,'utf8'),pause=()=>new Promise(r=>setTimeout(r,20));
(async()=>{
 const d=new JSDOM(read('voyageurs.html'),{url:'https://example.test/voyageurs.html',runScripts:'outside-only'}),w=d.window;
 const route={id:'R',short:'57R001',long:'Gare — Centre',file:'routes/test.json'},pattern={headsign:'Centre',stops:[{name:'Gare',lat:49,lon:6},{name:'Centre',lat:49.1,lon:6.1}],trips:[{id:'T',service:'S',times:[['08:00','08:00'],['08:15','08:15']]}]};let rows=[];
 w.setInterval=()=>1;w.AbortSignal=AbortSignal;
 w.fetch=async(url)=>({ok:true,json:async()=>String(url).includes('saeiv_live_courses')?rows:String(url).includes('services.json')?{services:{S:{start:'20260101',end:'20261231',days:[1,1,1,1,1,1,1]}}}:String(url).includes('test.json')?{patterns:[pattern]}:String(url).includes('routes.json')?{routes:[route]}:{}});
 for(const f of ['tracking-core.js','voyageurs.js'])w.eval(read(f));await pause();
 const select=(id,value)=>{const e=w.document.getElementById(id);e.value=value;e.dispatchEvent(new w.Event('change'))};
 select('date','2026-10-01');select('line','R');await pause();select('direction','0');select('stop','0');select('departure','0');
 const submit=async()=>{w.document.getElementById('journey').dispatchEvent(new w.Event('submit',{cancelable:true}));await pause()};
 rows=[{public_id:'p',stage:'hlp',delay_seconds:-180,observed_at:new Date().toISOString(),start_index:0,stop_index:0}];await submit();
 assert.match(w.document.getElementById('vehicles').textContent,/Passage estimé à 08:00/);
 rows[0].delay_seconds=180;await submit();assert.match(w.document.getElementById('vehicles').textContent,/08:03/);
 rows[0].observed_at=new Date(Date.now()-120000).toISOString();await submit();assert.match(w.document.getElementById('vehicles').textContent,/Suivi momentanément indisponible/);
 rows[0].served_stop_indices=[1];await submit();assert.equal(w.document.getElementById('vehicles').children.length,0);
 rows=[];await submit();assert.match(w.document.getElementById('summary').textContent,/ne signifie pas/);
 d.window.close();
 const h=new JSDOM('<div id="v13Userbar"></div><select id="startStop"><option value="0">0</option></select>',{url:'https://example.test/app.html',runScripts:'outside-only'}),v=h.window;
 let baseCalls=0,origins=[],callback,uploads=[],deleted=0;
 v.setInterval=()=>1;v.state={running:false,mode:null,pos:null,service:{mode:'regular'},dept:'57',route,pattern,run:{trip:pattern.trips[0],serviceDate:new Date('2026-10-01T00:00:00+02:00')}};
 v.startGps=()=>{baseCalls++;v.state.running=true;v.state.mode='gps';v.state.departed=false};v.dist=()=>5000;v.say=()=>{};
 Object.defineProperty(v.navigator,'geolocation',{value:{getCurrentPosition(resolve){resolve({timestamp:Date.now(),coords:{latitude:48.9,longitude:5.9,accuracy:10}})},watchPosition(cb){callback=cb;return 1},clearWatch(){}}});
 v.FluoOpsV29={routeWithAvoids:async(a,b)=>{origins.push(a);return{shape:[[a.lat,a.lon],[b.lat,b.lon]],distance:5000,duration:600,legs:[]}}};
 v.FluoFlatData={routes:async()=>({routes:[route]}),route:async()=>({patterns:[pattern]})};
 for(const f of ['tracking-core.js','v144-day-hlp-driver.js','v182-live-tracking.js'])v.eval(read(f));
 await v.startGps();await pause();assert.equal(baseCalls,0);assert.equal(origins[0].lat,48.9);assert(v.MonSAEIVDayAutopilotV144.snapshot.running);
 await v.startGps();assert.equal(origins.length,1,'No restart during HLP');
 v.MonSAEIVCloudV156={user:{id:'driver'},profile:{organization_id:'org'},client:{from(){return{async upsert(row){uploads.push(row);return{}},delete(){return{async eq(){deleted++;return{}}}}}}}};
 await v.MonSAEIVLiveV182.tick();assert.equal(uploads.at(-1).stage,'hlp');assert(!('origin' in uploads.at(-1)));
 await callback({timestamp:Date.now(),coords:{latitude:49,longitude:6,accuracy:10}});assert.equal(baseCalls,1);assert.equal(v.MonSAEIVDayAutopilotV144.snapshot,null);
 await v.MonSAEIVLiveV182.tick();assert.equal(uploads.at(-1).stage,'waiting');
 v.state.mode='simulation';await v.MonSAEIVLiveV182.tick();assert.equal(deleted,1,'Simulation removes the public position');
 assert.match(v.localStorage.getItem('mon-saeiv-hlp-journal-v182'),/HLP_START/);assert.match(v.localStorage.getItem('mon-saeiv-hlp-journal-v182'),/HLP_END/);
 h.window.close();console.log('PASS: passenger selectors, early/delay/stale/no-data/TAD; GPS HLP start, no duplicate start, arrival transition, publication, simulation exclusion, journal');
})().catch(e=>{console.error(e);process.exit(1)});
