'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const read=p=>fs.readFileSync(p,'utf8');
const visual=read('v202-antoni-pilot.js');
const board=read('v165-exploitation-board.js');
const planner=read('v187-collaborative-planning.js');
const day=read('v198-planning-ux.js');
const monitor=read('v183-live-supervision.js');
const inbox=read('v188-driver-inbox.js');
for(const f of ['v202-antoni-pilot.js','v165-exploitation-board.js','v187-collaborative-planning.js','v198-planning-ux.js','v183-live-supervision.js','v188-driver-inbox.js'])
 new vm.Script(read(f),{filename:f});
assert(visual.includes("const permitted=()=>"),'dispatcher role, not hardcoded company');
assert(visual.includes('saeiv-shared-ops'),'shared component styles');
assert(!visual.includes('saeiv-antoni-pilot #'),'no old Antoni-specific theme');
assert(visual.includes("const start=q('v165Date'),end=q('v190End')"),'same real date inputs retained and relocated');
assert(visual.includes("openCalendar(id,b)"),'separate usable calendar control on iPhone and desktop');
assert(!visual.includes('showPicker?.()'),'avoid duplicate native showPicker invocation on click');
assert(visual.includes('saeivWorkToggle'),'single board can show/hide toolbox');
assert(visual.includes('MonSAEIVPlanningUXV198?.choose?.'),'same driver detail as base');
assert(board.includes("const date=q('v165Date').value"),'date change goes through board');
assert(board.includes('multiSelected.clear();B.segments=[];'),'no stale previous-day courses');
assert(planner.includes('Tenancy changes data, not scoring rules'),'shared planning engine');
assert(planner.includes('const cost=x=>x.rank.incremental'), 'same company-agnostic economy scoring');
assert(planner.includes('{economicRouting:true}'),'same HLP and cuts in every company');
assert(day.includes("economicRouting:true"),'same checks in driver-day validation');
assert(monitor.includes("setMobileView('list')"),'responsive vehicles list remains');
assert(monitor.includes('data-v183-id'),'per-bus list details');
assert(monitor.includes("openVehicle(b.dataset.v183Id)"),'tapping bus opens detail, not forced map');
assert(monitor.includes("recipient_user_id:row.owner_id"),'message addressed to current bus driver');
assert(monitor.includes("String(row.organization_id)!==String(c.profile.organization_id)"),'same-company client authorization');
assert(monitor.includes("kind:'dispatch_direct'"),'realtime notification kind');
assert(inbox.includes("payload?.eventType==='INSERT'"),'push alert immediately on Realtime insert');
assert(inbox.includes("showDirect(payload.new)"),'driver receives direct alert');
assert(inbox.includes("Date.now()-I.lastDirectPoll<15000"),'15-second fallback when Realtime unavailable');
assert(inbox.includes('recipient_user_id',inbox.indexOf('function showDirect')),'recipient validation');
const sql=read('supabase/migrations/20261010164000_dispatch_direct_notifications.sql');
assert(sql.includes("private.is_exploitation_for(organization_id)"),'RLS same company');
assert(sql.includes("p.role='driver' and p.active"),'RLS recipient is active driver');
assert(sql.includes("read_at is null"),'sent notifications unread by default');
console.log('v1.0.116 shared dispatcher UI, date controls, common economy engine, list/map bus messaging and scoped RLS contracts validated');
